# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v5-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v5-dependencies-{{ checksum "yarn.lock" }}
        
      # run tests!
      - run: yarn build
      - run: cd packages/vue-apollo-option && yarn test:eslint
      - run: cd packages/vue-apollo-option && yarn test:types
      - run: cd packages/vue-apollo-option && yarn test:unit
      - run: cd packages/vue-apollo-components && yarn test:eslint
      - run: cd packages/vue-apollo-components && yarn test:types
      - run: cd packages/vue-apollo-components && yarn test:unit
      - run: cd packages/test-e2e && yarn test:e2e
      - run: cd packages/test-e2e-composition && yarn test:e2e
      - run: cd packages/test-ssr && yarn test:e2e

      - store_artifacts:
          path: packages/test-e2e/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-e2e-composition/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e-composition/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-ssr/tests/e2e/videos
      - store_artifacts:
          path: packages/test-ssr/tests/e2e/screenshots


