# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: cypress/base:14
        environment:
          ## this enables colors in the output
          TERM: xterm
      
    working_directory: ~/repo

    steps:
      - checkout

      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - run: export NVM_DIR="$HOME/.nvm"
      - run: [-s "$NVM_DIR/nvm.sh"] && \. "$NVM_DIR/nvm.sh"

      - run: nvm install 16
      - run: nvm use 16

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v10-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v10-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/docs/node_modules
            - packages/test-e2e/node_modules
            - packages/test-e2e-composition/node_modules
            - packages/test-e2e-composable-vue3/node_modules
            - packages/test-ssr/node_modules
            - packages/test-ssr-composition/node_modules
            - packages/vue-apollo-components/node_modules
            - packages/vue-apollo-composable/node_modules
            - packages/vue-apollo-option/node_modules
            - packages/vue-apollo-ssr/node_modules
            - packages/vue-apollo-util/node_modules
            - ~/.cache
          key: v10-dependencies-{{ checksum "yarn.lock" }}
        
      # run tests!
      - run: yarn lint
      - run: yarn build
      - run: cd packages/vue-apollo-option && yarn test:types
      - run: cd packages/vue-apollo-option && yarn test:unit
      - run: cd packages/vue-apollo-composable && yarn test:types
      - run: cd packages/test-e2e && yarn test:e2e
    #   - run: cd packages/test-e2e-composition && yarn test:e2e
      - run: cd packages/test-e2e-composable-vue3 && yarn test:e2e
    #   - run: cd packages/test-ssr && yarn test:e2e
    #   - run: cd packages/test-ssr-composition && yarn test:e2e

      - store_artifacts:
          path: packages/test-e2e/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-e2e-composition/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e-composition/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-e2e-composable-vue3/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e-composable-vue3/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-ssr/tests/e2e/videos
      - store_artifacts:
          path: packages/test-ssr/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-ssr-composition/tests/e2e/videos
      - store_artifacts:
          path: packages/test-ssr-composition/tests/e2e/screenshots


