# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: cypress/base:14
        environment:
          ## this enables colors in the output
          TERM: xterm
      
    working_directory: ~/repo

    steps:
      - checkout

      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - run: |
          echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
          echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV

      - run: |
          nvm install 16
          nvm use 16
          nvm alias default 16

      - run: npm install -g pnpm

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v11-dependencies-{{ checksum "pnpm-lock.yaml" }}
          # fallback to using the latest cache if no exact match is found
          - v11-dependencies-

      - run: pnpm install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - packages/docs/node_modules
            - packages/test-e2e/node_modules
            - packages/test-e2e-composition/node_modules
            - packages/test-e2e-composable-vue3/node_modules
            - packages/test-ssr/node_modules
            - packages/test-ssr-composition/node_modules
            - packages/vue-apollo-components/node_modules
            - packages/vue-apollo-composable/node_modules
            - packages/vue-apollo-option/node_modules
            - packages/vue-apollo-ssr/node_modules
            - packages/vue-apollo-util/node_modules
            - ~/.cache
            - ~/.pnpm-store
          key: v11-dependencies-{{ checksum "pnpm-lock.yaml" }}
        
      # run tests!
      - run: pnpm run lint
      - run: pnpm run build
      - run: cd packages/vue-apollo-option && pnpm run test:types
      - run: cd packages/vue-apollo-option && pnpm run test:unit
      - run: cd packages/vue-apollo-composable && pnpm run test:types
      - run: cd packages/test-e2e && pnpm run test:e2e
    #   - run: cd packages/test-e2e-composition && pnpm run test:e2e
      - run: cd packages/test-e2e-composable-vue3 && pnpm run test:e2e
    #   - run: cd packages/test-ssr && pnpm run test:e2e
    #   - run: cd packages/test-ssr-composition && pnpm run test:e2e

      - store_artifacts:
          path: packages/test-e2e/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-e2e-composition/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e-composition/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-e2e-composable-vue3/tests/e2e/videos
      - store_artifacts:
          path: packages/test-e2e-composable-vue3/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-ssr/tests/e2e/videos
      - store_artifacts:
          path: packages/test-ssr/tests/e2e/screenshots
      - store_artifacts:
          path: packages/test-ssr-composition/tests/e2e/videos
      - store_artifacts:
          path: packages/test-ssr-composition/tests/e2e/screenshots


